apiVersion: v1
kind: Service
metadata:
 name: purple-service
 namespace: whale
spec:
  type: NodePort
  selector:
    app: purple-whale
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000